CXXFLAGS=  -Wall  -I.  -O3

MPIRUN=/software/MPI/openmpi-1.4.1_gcc/bin/mpirun
MPICC=/software/MPI/openmpi-1.4.1_gcc/bin/mpic++

all: Ray

OBJECTS= Machine.o common_functions.o Loader.o ray_main.o Read.o MyAllocator.o SffLoader.o Parameters.o Vertex.o ReadAnnotation.o CoverageDistribution.o Message.o  Direction.o


%.o: %.cpp
	$(MPICC) $(CXXFLAGS) -c $< -o $@


Ray: ray_main.o $(OBJECTS)
	$(MPICC) $(CXXFLAGS) $^ -o $@


clean:
	rm -f *.o Ray
