SequencesIndexer-y += code/SequencesIndexer/SequencesIndexer.o 
SequencesIndexer-y += code/SequencesIndexer/IndexerWorker.o 
SequencesIndexer-y += code/SequencesIndexer/PairedRead.o
SequencesIndexer-y += code/SequencesIndexer/ReadAnnotation.o 

obj-y += $(SequencesIndexer-y)



