/*

Ray
Copyright (C)  2010  Sébastien Boisvert

http://DeNovoAssembler.SourceForge.Net/

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You have received a copy of the GNU General Public License
along with this program (COPYING).  
see <http://www.gnu.org/licenses/>

*/

#ifndef __MALLOC_TYPES
#define __MALLOC_TYPES

extern const char* MALLOC_TYPES[];

enum{
RAY_MALLOC_TYPE_SEED_EXTENDER_CACHE,
RAY_MALLOC_TYPE_EXTENSION_DATA_TREES,
RAY_MALLOC_TYPE_EXTENSION_DATA_ALLOCATOR,
RAY_MALLOC_TYPE_LIBRARY_ALLOCATOR,
RAY_MALLOC_TYPE_AMOS,
RAY_MALLOC_TYPE_GRID_TABLE_DATA,
RAY_MALLOC_TYPE_GRID_TABLE_SIZES,
RAY_MALLOC_TYPE_VERTEX_TABLE_DATA,
RAY_MALLOC_TYPE_VERTEX_TABLE_SIZES,
RAY_MALLOC_TYPE_PERSISTENT_MESSAGE_RING,
RAY_MALLOC_TYPE_PERSISTENT_MESSAGE_BUFFERS,
RAY_MALLOC_TYPE_MEMORY_REDUCER_BUFFERS,
RAY_MALLOC_TYPE_LIBRARY_BUFFERS,
RAY_MALLOC_TYPE_FUSION_BUFFERS,
RAY_MALLOC_TYPE_FUSION_CACHING,
RAY_MALLOC_TYPE_LOADER_ALLOCATOR,
RAY_MALLOC_TYPE_INBOX_ALLOCATOR,
RAY_MALLOC_TYPE_OUTBOX_ALLOCATOR,
RAY_MALLOC_TYPE_INBOX_VECTOR,
RAY_MALLOC_TYPE_OUTBOX_VECTOR,
RAY_MALLOC_TYPE_PERSISTENT_DATA_ALLOCATOR,
RAY_MALLOC_TYPE_WAVE_ALLOCATOR,
RAY_MALLOC_TYPE_DATA_ALLOCATOR,
RAY_MALLOC_TYPE_454,
RAY_MALLOC_TYPE_VERTEX_EXTRACTOR_BUFFERS,
RAY_MALLOC_TYPE_OUTGOING_EDGES_EXTRACTOR_BUFFERS,
RAY_MALLOC_TYPE_INGOING_EDGES_EXTRACTOR_BUFFERS,
RAY_MALLOC_TYPE_DEL_OUT,
RAY_MALLOC_TYPE_DEL_IN,
RAY_MALLOC_TYPE_BZ2,
RAY_MALLOC_TYPE_DUMMY
};

#endif
