
g++ test_kmer.cpp common_functions.cpp Kmer.cpp crypto.cpp  -I. -D MAXKMERLENGTH=32 -DASSERT
./a.out TGAAATGGAAATGGTCTGGGAAG

g++ test_kmer.cpp common_functions.cpp Kmer.cpp crypto.cpp  -I. -D MAXKMERLENGTH=64 -DASSERT
./a.out \
TGAAATGGAAATGGTCTGGGAAAAACAACTAAAAGATATTATTGTAGTA

g++ test_kmer.cpp common_functions.cpp Kmer.cpp crypto.cpp  -I. -D MAXKMERLENGTH=96 -DASSERT
./a.out \
TGAAATGGAAATGGTCTGGGAAAAACAACTAAAAGATATTATTGTAGTAGCTGGTTTTGAAATTTATGACGCTGAAATAACTCCCCACTA

g++ test_kmer.cpp common_functions.cpp Kmer.cpp crypto.cpp  -I. -D MAXKMERLENGTH=128 -DASSERT
./a.out \
TGAAATGGAAATGGTCTGGGAAAAACAACTAAAAGATATTATTGTAGTAGCTGGTTTTGAAATTTATGACGCTGAAATAACTCCCCACTATATTTTCACCAAATTTATT

g++ test_kmer.cpp common_functions.cpp Kmer.cpp crypto.cpp  -I. -D MAXKMERLENGTH=75 -DASSERT
./a.out \
TGAAATGGAAATGGTCTGGGAAAAACAACTAAAAGATATTATTGTAGTAGCTGGTTTTGAAATTTATGACGCT

g++ test_kmer.cpp common_functions.cpp Kmer.cpp crypto.cpp  -I. -D MAXKMERLENGTH=50 -DASSERT
./a.out \
TGAAATGGAAATGGTCTGGGAAAAACAACTAAAAGATATTAT
