VerticesExtractor-y += code/VerticesExtractor/VerticesExtractor.o 
VerticesExtractor-y += code/VerticesExtractor/GridTable.o
VerticesExtractor-y += code/VerticesExtractor/GridTableIterator.o
VerticesExtractor-y += code/VerticesExtractor/Vertex.o

obj-y += $(VerticesExtractor-y)



