

KmerAcademyBuilder-y += assembler/KmerAcademyBuilder_adapters.o
KmerAcademyBuilder-y += assembler/KmerAcademyBuilder.o
KmerAcademyBuilder-y +=  structures/BloomFilter.o
KmerAcademyBuilder-y += structures/Kmer.o
KmerAcademyBuilder-y += graph/KmerAcademy.o graph/KmerAcademyIterator.o

obj-y += $(KmerAcademyBuilder-y)

