

KmerAcademyBuilder-y += plugin_KmerAcademyBuilder/KmerAcademyBuilder.o
KmerAcademyBuilder-y +=  plugin_KmerAcademyBuilder/BloomFilter.o
KmerAcademyBuilder-y += plugin_KmerAcademyBuilder/Kmer.o

obj-y += $(KmerAcademyBuilder-y)

