KmerAcademyBuilder-y += code/plugin_KmerAcademyBuilder/KmerAcademyBuilder.o
KmerAcademyBuilder-y += code/plugin_KmerAcademyBuilder/BloomFilter.o
KmerAcademyBuilder-y += code/plugin_KmerAcademyBuilder/Kmer.o

obj-y += $(KmerAcademyBuilder-y)
