
FusionTaskCreator-y += assembler/FusionTaskCreator_adapters.o
FusionTaskCreator-y += assembler/FusionWorker.o 
FusionTaskCreator-y += assembler/FusionTaskCreator.o 

obj-y += $(FusionTaskCreator-y)

