SequencesIndexer-y += code/plugin_SequencesIndexer/SequencesIndexer.o 
SequencesIndexer-y += code/plugin_SequencesIndexer/IndexerWorker.o 
SequencesIndexer-y += code/plugin_SequencesIndexer/PairedRead.o
SequencesIndexer-y += code/plugin_SequencesIndexer/ReadAnnotation.o 

obj-y += $(SequencesIndexer-y)



