
SequencesIndexer-y += plugin_SequencesIndexer/SequencesIndexer.o 
SequencesIndexer-y += plugin_SequencesIndexer/IndexerWorker.o 
SequencesIndexer-y +=  plugin_SequencesIndexer/PairedRead.o plugin_SequencesIndexer/ReadAnnotation.o 

obj-y += $(SequencesIndexer-y)



