
SequencesIndexer-y += assembler/SequencesIndexer_adapters.o 
SequencesIndexer-y += assembler/SequencesIndexer.o 
SequencesIndexer-y += assembler/IndexerWorker.o 
SequencesIndexer-y +=  structures/PairedRead.o structures/ReadAnnotation.o 

obj-y += $(SequencesIndexer-y)



