
Scaffolder-y += scaffolder/Scaffolder_adapters.o
Scaffolder-y += scaffolder/Scaffolder.o 
Scaffolder-y += scaffolder/ScaffoldingLink.o
Scaffolder-y += scaffolder/SummarizedLink.o
Scaffolder-y += scaffolder/ScaffoldingAlgorithm.o
Scaffolder-y += scaffolder/ScaffoldingVertex.o
Scaffolder-y += scaffolder/ScaffoldingEdge.o


obj-y += $(Scaffolder-y)



