
Scaffolder-y += plugin_Scaffolder/Scaffolder.o 
Scaffolder-y += plugin_Scaffolder/ScaffoldingLink.o
Scaffolder-y += plugin_Scaffolder/SummarizedLink.o
Scaffolder-y += plugin_Scaffolder/ScaffoldingAlgorithm.o
Scaffolder-y += plugin_Scaffolder/ScaffoldingVertex.o
Scaffolder-y += plugin_Scaffolder/ScaffoldingEdge.o


obj-y += $(Scaffolder-y)



