Scaffolder-y += code/plugin_Scaffolder/Scaffolder.o 
Scaffolder-y += code/plugin_Scaffolder/ScaffoldingLink.o
Scaffolder-y += code/plugin_Scaffolder/SummarizedLink.o
Scaffolder-y += code/plugin_Scaffolder/ScaffoldingAlgorithm.o
Scaffolder-y += code/plugin_Scaffolder/ScaffoldingVertex.o
Scaffolder-y += code/plugin_Scaffolder/ScaffoldingEdge.o

obj-y += $(Scaffolder-y)
