PhylogenyViewer-y += code/plugin_PhylogenyViewer/PhylogenyViewer.o
PhylogenyViewer-y += code/plugin_PhylogenyViewer/GenomeToTaxonLoader.o
PhylogenyViewer-y += code/plugin_PhylogenyViewer/PhylogeneticTreeLoader.o
PhylogenyViewer-y += code/plugin_PhylogenyViewer/TaxonNameLoader.o

obj-y += $(PhylogenyViewer-y)
