
PhylogenyViewer-y += plugin_PhylogenyViewer/PhylogenyViewer.o
PhylogenyViewer-y += plugin_PhylogenyViewer/PhylogenyViewer_adapters.o
PhylogenyViewer-y += plugin_PhylogenyViewer/GenomeToTaxonLoader.o
PhylogenyViewer-y += plugin_PhylogenyViewer/PhylogeneticTreeLoader.o
PhylogenyViewer-y += plugin_PhylogenyViewer/TaxonNameLoader.o

obj-y += $(PhylogenyViewer-y)

