
PhylogenyViewer-y += plugin_PhylogenyViewer/PhylogenyViewer.o
PhylogenyViewer-y += plugin_PhylogenyViewer/PhylogenyViewer_adapters.o
PhylogenyViewer-y += plugin_PhylogenyViewer/GenomeToTaxonLoader.o

obj-y += $(PhylogenyViewer-y)

