GenomeNeighbourhood-y += code/plugin_GenomeNeighbourhood/GenomeNeighbourhood.o
GenomeNeighbourhood-y += code/plugin_GenomeNeighbourhood/Neighbour.o
GenomeNeighbourhood-y += code/plugin_GenomeNeighbourhood/NeighbourPair.o

obj-y += $(GenomeNeighbourhood-y)
