Searcher-y += code/Searcher/Searcher.o
Searcher-y += code/Searcher/SearchDirectory.o
Searcher-y += code/Searcher/ContigSearchEntry.o
Searcher-y += code/Searcher/ContigHit.o
Searcher-y += code/Searcher/ColorSet.o
Searcher-y += code/Searcher/VirtualKmerColor.o
Searcher-y += code/Searcher/QualityCaller.o
Searcher-y += code/Searcher/DistributionWriter.o
Searcher-y += code/Searcher/ColoredPeakFinder.o

obj-y += $(Searcher-y)
