/*
 	Ray
    Copyright (C) 2011  Sébastien Boisvert

	http://DeNovoAssembler.SourceForge.Net/

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You have received a copy of the GNU General Public License
    along with this program (COPYING).  
	see <http://www.gnu.org/licenses/>

*/

MACRO_LIST_ITEM( RAY_MALLOC_TYPE_SEED_EXTENDER_CACHE )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_EXTENSION_DATA_TREES )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_EXTENSION_DATA_ALLOCATOR )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_LIBRARY_ALLOCATOR )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_AMOS )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_GRID_TABLE_DATA )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_GRID_TABLE_SIZES )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_VERTEX_TABLE_DATA )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_VERTEX_TABLE_SIZES )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_PERSISTENT_MESSAGE_RING )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_PERSISTENT_MESSAGE_BUFFERS )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_MEMORY_REDUCER_BUFFERS )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_LIBRARY_BUFFERS )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_FUSION_BUFFERS )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_FUSION_CACHING )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_LOADER_ALLOCATOR )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_INBOX_ALLOCATOR )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_OUTBOX_ALLOCATOR )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_INBOX_VECTOR )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_OUTBOX_VECTOR )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_PERSISTENT_DATA_ALLOCATOR )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_WAVE_ALLOCATOR )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_DATA_ALLOCATOR )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_454 )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_VERTEX_EXTRACTOR_BUFFERS )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_OUTGOING_EDGES_EXTRACTOR_BUFFERS )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_INGOING_EDGES_EXTRACTOR_BUFFERS )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_DEL_OUT )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_DEL_IN )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_BZ2 )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_KMER_ACADEMY )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_KMER_ACADEMY_BUFFER )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_OPTIMAL_READ_MARKERS )
MACRO_LIST_ITEM( RAY_MALLOC_TYPE_OPTIMAL_READ_MARKER_WORKERS )

