
Searcher-y += search-engine/Searcher_adapters.o
Searcher-y += search-engine/Searcher.o
Searcher-y += search-engine/SearchDirectory.o
Searcher-y += search-engine/ContigSearchEntry.o
Searcher-y += search-engine/ContigHit.o
Searcher-y += search-engine/ColorSet.o
Searcher-y += search-engine/VirtualKmerColor.o

obj-y += $(Searcher-y)

