
Searcher-y += plugin_Searcher/Searcher_adapters.o
Searcher-y += plugin_Searcher/Searcher.o
Searcher-y += plugin_Searcher/SearchDirectory.o
Searcher-y += plugin_Searcher/ContigSearchEntry.o
Searcher-y += plugin_Searcher/ContigHit.o
Searcher-y += plugin_Searcher/ColorSet.o
Searcher-y += plugin_Searcher/VirtualKmerColor.o
Searcher-y += plugin_Searcher/QualityCaller.o
Searcher-y += plugin_Searcher/DistributionWriter.o

obj-y += $(Searcher-y)

