
JoinerTaskCreator-y += assembler/JoinerTaskCreator_adapters.o
JoinerTaskCreator-y += assembler/JoinerWorker.o 
JoinerTaskCreator-y += assembler/JoinerTaskCreator.o

obj-y += $(JoinerTaskCreator-y)



