/*
 	Ray
    Copyright (C) 2012  Sébastien Boisvert

	http://DeNovoAssembler.SourceForge.Net/

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You have received a copy of the GNU General Public License
    along with this program (COPYING).  
	see <http://www.gnu.org/licenses/>

*/


// this file contains the reply tags

MACRO_LIST_ITEM( RAY_MPI_TAG_GET_CONTIG_CHUNK,		RAY_MPI_TAG_GET_CONTIG_CHUNK_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_REQUEST_VERTEX_READS,	RAY_MPI_TAG_REQUEST_VERTEX_READS_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_GET_READ_MATE, 		RAY_MPI_TAG_GET_READ_MATE_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_REQUEST_VERTEX_COVERAGE,	RAY_MPI_TAG_REQUEST_VERTEX_COVERAGE_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_ATTACH_SEQUENCE,		RAY_MPI_TAG_ATTACH_SEQUENCE_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_GET_VERTEX_EDGES_COMPACT,	RAY_MPI_TAG_GET_VERTEX_EDGES_COMPACT_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_HAS_PAIRED_READ,		RAY_MPI_TAG_HAS_PAIRED_READ_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_GET_READ_MARKERS,		RAY_MPI_TAG_GET_READ_MARKERS_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_GET_PATH_LENGTH,		RAY_MPI_TAG_GET_PATH_LENGTH_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_GET_COVERAGE_AND_DIRECTION,	RAY_MPI_TAG_GET_COVERAGE_AND_DIRECTION_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_SCAFFOLDING_LINKS, 		RAY_MPI_TAG_SCAFFOLDING_LINKS_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_CONTIG_INFO,			RAY_MPI_TAG_CONTIG_INFO_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_ASK_READ_LENGTH, 		RAY_MPI_TAG_ASK_READ_LENGTH_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_ASK_VERTEX_PATHS_SIZE, 	RAY_MPI_TAG_ASK_VERTEX_PATHS_SIZE_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_ASK_VERTEX_PATH, 		RAY_MPI_TAG_ASK_VERTEX_PATH_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_GET_PATH_VERTEX, 		RAY_MPI_TAG_GET_PATH_VERTEX_REPLY )

MACRO_LIST_ITEM( RAY_MPI_TAG_VERTEX_INFO,			RAY_MPI_TAG_VERTEX_INFO_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_REQUEST_READ_SEQUENCE, 		RAY_MPI_TAG_REQUEST_READ_SEQUENCE_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_REQUEST_VERTEX_OUTGOING_EDGES, 	RAY_MPI_TAG_REQUEST_VERTEX_OUTGOING_EDGES_REPLY )
MACRO_LIST_ITEM( RAY_MPI_TAG_TEST_NETWORK_MESSAGE, 		RAY_MPI_TAG_TEST_NETWORK_MESSAGE_REPLY )

