/*
 	Ray
    Copyright (C) 2012  Sébastien Boisvert

	http://DeNovoAssembler.SourceForge.Net/

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You have received a copy of the GNU General Public License
    along with this program (COPYING).  
	see <http://www.gnu.org/licenses/>

*/

// this is a list of wake-up switches for slave modes

MACRO_LIST_ITEM( RAY_MPI_TAG_TEST_NETWORK, 		RAY_SLAVE_MODE_TEST_NETWORK )
MACRO_LIST_ITEM( RAY_MPI_TAG_COUNT_SEARCH_ELEMENTS, 	RAY_SLAVE_MODE_COUNT_SEARCH_ELEMENTS )
MACRO_LIST_ITEM( RAY_MPI_TAG_START_SCAFFOLDER, 		RAY_SLAVE_MODE_SCAFFOLDER )
MACRO_LIST_ITEM( RAY_MPI_TAG_LOAD_SEQUENCES, RAY_SLAVE_MODE_LOAD_SEQUENCES )
MACRO_LIST_ITEM( RAY_MPI_TAG_START_INDEXING_SEQUENCES, RAY_SLAVE_MODE_INDEX_SEQUENCES )
MACRO_LIST_ITEM( RAY_MPI_TAG_START_VERTICES_DISTRIBUTION, RAY_SLAVE_MODE_BUILD_KMER_ACADEMY )
MACRO_LIST_ITEM( RAY_MPI_TAG_PREPARE_COVERAGE_DISTRIBUTION, RAY_SLAVE_MODE_SEND_DISTRIBUTION )
MACRO_LIST_ITEM( RAY_MPI_TAG_START_SEEDING, RAY_SLAVE_MODE_START_SEEDING )
MACRO_LIST_ITEM( RAY_MPI_TAG_REQUEST_SEED_LENGTHS, RAY_SLAVE_MODE_SEND_SEED_LENGTHS )
MACRO_LIST_ITEM( RAY_MPI_TAG_GOOD_JOB_SEE_YOU_SOON, RAY_SLAVE_MODE_DIE )
MACRO_LIST_ITEM( RAY_MPI_TAG_ASK_EXTENSION, RAY_SLAVE_MODE_EXTENSION )
MACRO_LIST_ITEM( RAY_MPI_TAG_ASK_EXTENSION_DATA, RAY_SLAVE_MODE_SEND_EXTENSION_DATA )

MACRO_LIST_ITEM( RAY_MPI_TAG_ASSEMBLE_WAVES, RAY_SLAVE_MODE_ASSEMBLE_WAVES )
MACRO_LIST_ITEM( RAY_MPI_TAG_START_FUSION, RAY_SLAVE_MODE_FUSION )
MACRO_LIST_ITEM( RAY_MPI_TAG_FINISH_FUSIONS, RAY_SLAVE_MODE_FINISH_FUSIONS )
MACRO_LIST_ITEM( RAY_MPI_TAG_DISTRIBUTE_FUSIONS, RAY_SLAVE_MODE_DISTRIBUTE_FUSIONS )
MACRO_LIST_ITEM( RAY_MPI_TAG_WRITE_AMOS, RAY_SLAVE_MODE_AMOS )
MACRO_LIST_ITEM( RAY_MPI_TAG_AUTOMATIC_DISTANCE_DETECTION, RAY_SLAVE_MODE_AUTOMATIC_DISTANCE_DETECTION )
MACRO_LIST_ITEM( RAY_MPI_TAG_ASK_LIBRARY_DISTANCES, RAY_SLAVE_MODE_SEND_LIBRARY_DISTANCES )
MACRO_LIST_ITEM( RAY_MPI_TAG_COUNT_FILE_ENTRIES, RAY_SLAVE_MODE_COUNT_FILE_ENTRIES )





