/*
 	Ray
    Copyright (C) 2011  Sébastien Boisvert

	http://DeNovoAssembler.SourceForge.Net/

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You have received a copy of the GNU General Public License
    along with this program (COPYING).  
	see <http://www.gnu.org/licenses/>

*/

MACRO_LIST_ITEM( RAY_MASTER_MODE_LOAD_CONFIG )
MACRO_LIST_ITEM( RAY_MASTER_MODE_LOAD_SEQUENCES )
MACRO_LIST_ITEM( RAY_MASTER_MODE_TRIGGER_VERTICE_DISTRIBUTION )
MACRO_LIST_ITEM( RAY_MASTER_MODE_SEND_COVERAGE_VALUES )
MACRO_LIST_ITEM( RAY_MASTER_MODE_START_EDGES_DISTRIBUTION )
MACRO_LIST_ITEM( RAY_MASTER_MODE_DO_NOTHING )
MACRO_LIST_ITEM( RAY_MASTER_MODE_UPDATE_DISTANCES )
MACRO_LIST_ITEM( RAY_MASTER_MODE_ASK_EXTENSIONS )
MACRO_LIST_ITEM( RAY_MASTER_MODE_AMOS )
MACRO_LIST_ITEM( RAY_MASTER_MODE_PREPARE_DISTRIBUTIONS )
MACRO_LIST_ITEM( RAY_MASTER_MODE_TRIGGER_INDEXING )
MACRO_LIST_ITEM( RAY_MASTER_MODE_INDEX_SEQUENCES )
MACRO_LIST_ITEM( RAY_MASTER_MODE_PREPARE_DISTRIBUTIONS_WITH_ANSWERS )
MACRO_LIST_ITEM( RAY_MASTER_MODE_PREPARE_SEEDING )
MACRO_LIST_ITEM( RAY_MASTER_MODE_TRIGGER_SEEDING )
MACRO_LIST_ITEM( RAY_MASTER_MODE_TRIGGER_DETECTION )
MACRO_LIST_ITEM( RAY_MASTER_MODE_ASK_DISTANCES )
MACRO_LIST_ITEM( RAY_MASTER_MODE_START_UPDATING_DISTANCES )
MACRO_LIST_ITEM( RAY_MASTER_MODE_TRIGGER_EXTENSIONS )
MACRO_LIST_ITEM( RAY_MASTER_MODE_TRIGGER_FUSIONS )
MACRO_LIST_ITEM( RAY_MASTER_MODE_TRIGGER_FIRST_FUSIONS )
MACRO_LIST_ITEM( RAY_MASTER_MODE_START_FUSION_CYCLE )
MACRO_LIST_ITEM( RAY_MASTER_MODE_SCAFFOLDER )
MACRO_LIST_ITEM( RAY_MASTER_MODE_KILL_RANKS )
MACRO_LIST_ITEM( RAY_MASTER_MODE_WRITE_SCAFFOLDS )
MACRO_LIST_ITEM( RAY_MASTER_MODE_TRIGGER_GRAPH_BUILDING )
MACRO_LIST_ITEM( RAY_MASTER_MODE_PURGE_NULL_EDGES )
MACRO_LIST_ITEM( RAY_MASTER_MODE_WRITE_KMERS )
MACRO_LIST_ITEM( RAY_MASTER_MODE_KILL_ALL_MPI_RANKS )
MACRO_LIST_ITEM( RAY_MASTER_MODE_TEST_NETWORK )
MACRO_LIST_ITEM( RAY_MASTER_MODE_COUNT_FILE_ENTRIES )

