SeedExtender-y += code/SeedExtender/SeedExtender.o 
SeedExtender-y += code/SeedExtender/Direction.o
SeedExtender-y += code/SeedExtender/VertexMessenger.o
SeedExtender-y += code/SeedExtender/ReadFetcher.o
SeedExtender-y += code/SeedExtender/BubbleTool.o
SeedExtender-y += code/SeedExtender/Chooser.o
SeedExtender-y += code/SeedExtender/OpenAssemblerChooser.o
SeedExtender-y += code/SeedExtender/TipWatchdog.o
SeedExtender-y += code/SeedExtender/NovaEngine.o
SeedExtender-y += code/SeedExtender/ExtensionElement.o 
SeedExtender-y += code/SeedExtender/DepthFirstSearchData.o 
SeedExtender-y += code/SeedExtender/ExtensionData.o 

obj-y += $(SeedExtender-y)
