SeedExtender-y += code/plugin_SeedExtender/SeedExtender.o 
SeedExtender-y += code/plugin_SeedExtender/Direction.o
SeedExtender-y += code/plugin_SeedExtender/VertexMessenger.o
SeedExtender-y += code/plugin_SeedExtender/ReadFetcher.o
SeedExtender-y += code/plugin_SeedExtender/BubbleTool.o
SeedExtender-y += code/plugin_SeedExtender/Chooser.o
SeedExtender-y += code/plugin_SeedExtender/OpenAssemblerChooser.o
SeedExtender-y += code/plugin_SeedExtender/TipWatchdog.o
SeedExtender-y += code/plugin_SeedExtender/NovaEngine.o
SeedExtender-y += code/plugin_SeedExtender/ExtensionElement.o 
SeedExtender-y += code/plugin_SeedExtender/DepthFirstSearchData.o 
SeedExtender-y += code/plugin_SeedExtender/ExtensionData.o 

obj-y += $(SeedExtender-y)
