
SeedExtender-y += plugin_SeedExtender/SeedExtender.o
SeedExtender-y +=  plugin_SeedExtender/Direction.o
SeedExtender-y += plugin_SeedExtender/VertexMessenger.o plugin_SeedExtender/ReadFetcher.o
SeedExtender-y += plugin_SeedExtender/BubbleTool.o plugin_SeedExtender/Chooser.o plugin_SeedExtender/OpenAssemblerChooser.o
SeedExtender-y += plugin_SeedExtender/TipWatchdog.o plugin_SeedExtender/NovaEngine.o
SeedExtender-y += plugin_SeedExtender/ExtensionElement.o 
SeedExtender-y += plugin_SeedExtender/DepthFirstSearchData.o 
SeedExtender-y += plugin_SeedExtender/ExtensionData.o 

obj-y += $(SeedExtender-y)



