
SeedExtender-y += assembler/SeedExtender_adapters.o
SeedExtender-y += assembler/SeedExtender.o
SeedExtender-y +=  structures/Direction.o
SeedExtender-y += assembler/VertexMessenger.o assembler/ReadFetcher.o
SeedExtender-y += heuristics/BubbleTool.o heuristics/Chooser.o heuristics/OpenAssemblerChooser.o
SeedExtender-y += heuristics/TipWatchdog.o heuristics/NovaEngine.o
SeedExtender-y += assembler/ExtensionElement.o 
SeedExtender-y += assembler/DepthFirstSearchData.o 
SeedExtender-y += assembler/ExtensionData.o 

obj-y += $(SeedExtender-y)



