dydx=read.table('dydx.data')
y=read.table('y.data')
pdf('Fixed.pdf')
par(mfrow=c(2,1))
plot(y[[1]],log(y[[2]]),type='l',col='red',main='Coverage counts',xlab='Coverage',ylab='Count')
theMin=min(dydx[[2]])
print(theMin)
dydx[[2]]=dydx[[2]]+-theMin+1
print(dydx[[2]])
plot(dydx[[1]],log(dydx[[2]]),col='blue',type='l',main='Variation of coverage counts',xlab='Coverage',ylab='Count variation')
dev.off()
