TaxonomyViewer-y += code/TaxonomyViewer/TaxonomyViewer.o
TaxonomyViewer-y += code/TaxonomyViewer/GenomeToTaxonLoader.o
TaxonomyViewer-y += code/TaxonomyViewer/TaxonomicTreeLoader.o
TaxonomyViewer-y += code/TaxonomyViewer/TaxonNameLoader.o

obj-y += $(TaxonomyViewer-y)
