SpuriousSeedAnnihilator-y += code/SpuriousSeedAnnihilator/SpuriousSeedAnnihilator.o
SpuriousSeedAnnihilator-y += code/SpuriousSeedAnnihilator/AnnihilationWorker.o
SpuriousSeedAnnihilator-y += code/SpuriousSeedAnnihilator/SeedFilteringWorkflow.o
SpuriousSeedAnnihilator-y += code/SpuriousSeedAnnihilator/AttributeFetcher.o
SpuriousSeedAnnihilator-y += code/SpuriousSeedAnnihilator/AnnotationFetcher.o

obj-y += $(SpuriousSeedAnnihilator-y)
