SpuriousSeedAnnihilator-y += code/SpuriousSeedAnnihilator/SpuriousSeedAnnihilator.o
SpuriousSeedAnnihilator-y += code/SpuriousSeedAnnihilator/AnnihilationWorker.o
SpuriousSeedAnnihilator-y += code/SpuriousSeedAnnihilator/SeedFilteringWorkflow.o
SpuriousSeedAnnihilator-y += code/SpuriousSeedAnnihilator/AttributeFetcher.o
SpuriousSeedAnnihilator-y += code/SpuriousSeedAnnihilator/AnnotationFetcher.o
SpuriousSeedAnnihilator-y += code/SpuriousSeedAnnihilator/NanoMerger.o
SpuriousSeedAnnihilator-y += code/SpuriousSeedAnnihilator/SeedMergingWorkflow.o
SpuriousSeedAnnihilator-y += code/SpuriousSeedAnnihilator/GraphExplorer.o
SpuriousSeedAnnihilator-y += code/SpuriousSeedAnnihilator/GraphSearchResult.o
SpuriousSeedAnnihilator-y += code/SpuriousSeedAnnihilator/SeedGossipSolver.o

obj-y += $(SpuriousSeedAnnihilator-y)
