Surveyor-y += code/Surveyor/Mother.o
Surveyor-y += code/Surveyor/StoreKeeper.o
Surveyor-y += code/Surveyor/GenomeGraphReader.o
Surveyor-y += code/Surveyor/GenomeAssemblyReader.o
Surveyor-y += code/Surveyor/CoalescenceManager.o
Surveyor-y += code/Surveyor/ExperimentVertex.o
Surveyor-y += code/Surveyor/MatrixOwner.o
Surveyor-y += code/Surveyor/SequenceKmerReader.o

obj-y += $(Surveyor-y)
