KmerAcademyBuilder-y += code/KmerAcademyBuilder/KmerAcademyBuilder.o
KmerAcademyBuilder-y += code/KmerAcademyBuilder/BloomFilter.o
KmerAcademyBuilder-y += code/KmerAcademyBuilder/Kmer.o

obj-y += $(KmerAcademyBuilder-y)
