
VerticesExtractor-y += plugin_VerticesExtractor/VerticesExtractor_adapters.o
VerticesExtractor-y += plugin_VerticesExtractor/VerticesExtractor.o 
VerticesExtractor-y += plugin_VerticesExtractor/GridTable.o plugin_VerticesExtractor/GridTableIterator.o
VerticesExtractor-y += plugin_VerticesExtractor/Vertex.o

obj-y += $(VerticesExtractor-y)



