VerticesExtractor-y += code/plugin_VerticesExtractor/VerticesExtractor.o 
VerticesExtractor-y += code/plugin_VerticesExtractor/GridTable.o
VerticesExtractor-y += code/plugin_VerticesExtractor/GridTableIterator.o
VerticesExtractor-y += code/plugin_VerticesExtractor/Vertex.o

obj-y += $(VerticesExtractor-y)



