
VerticesExtractor-y += assembler/VerticesExtractor_adapters.o
VerticesExtractor-y += assembler/VerticesExtractor.o 
VerticesExtractor-y += graph/GridTable.o graph/GridTableIterator.o
VerticesExtractor-y += structures/Vertex.o

obj-y += $(VerticesExtractor-y)



